### ISSUE TITLE
Front end framework

### ISSUE THREAD

**Issue by nolwn** [nolwn/library-catalog#18]
We need to decide on a front end framework to use

**Comment by katrinasilver** [comment]
i have used this for my capstone project, the nice thing about this is, like Antd Design, they have a lot of ready-to-use components for a lot of UI's so we don't have to build them from scratch https://react.semantic-ui.com/
Caveat is that I haven't used it for react hooks but they look doable. Check out the code sandbox for the components. 👍

**Comment by nolwn** [comment]
We will use semantic!
