### ISSUE TITLE
UX Design

### ISSUE THREAD

**Issue by nolwn** [nolwn/library-catalog#26]
We need to figure out how UX is going to be designed, since we are all participating in this as programmers and we don't have a dedicate UX team. One or more of us should mock up some designs for our web app that we can use to build features. Those mock ups should be made with our front end framework of choice in mind. #18

**Comment by katrinasilver** [comment]
i'm happy to help here if you guys can describe how it should be used and who's going to use the web app. I will probably use hand-drawn wireframes though instead of high-fidelity mock-ups, assuming we will leverage our choice for #18 to dictate the appearance of the UI.

**Comment by nolwn** [comment]
Katrina is going to draw us up some wireframes!
